In [13]:
import numpy as np

In [14]:
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]

In [15]:
sales_array = np.array(sales)
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [16]:
print(f'ndim: {sales_array.ndim})')
print(f'shape: {sales_array.shape})')
print(f'size: {sales_array.size})')
print(f'dtype: {sales_array.dtype})')

ndim: 1)
shape: (10,))
size: 10)
dtype: int64)

In [17]:
#Array excercise
my_list = [x * 10 for x in range(1,11)]
my_list_array = np.array(my_list)
my_list_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [18]:
print(f'ndim: {my_list_array.ndim})')
print(f'shape: {my_list_array.shape})')
print(f'size: {my_list_array.size})')
print(f'dtype: {my_list_array.dtype})')

ndim: 1)
shape: (10,))
size: 10)
dtype: int64)

In [19]:
# Array Creation
np.ones(4,)

array([1., 1., 1., 1.])

In [20]:
np.zeros((2, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.linspace(0,100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [23]:
np.arange(1, 9, 2).reshape(2,2)

array([[1, 3],
       [5, 7]])

In [24]:
# Random number arrays
from numpy.random import default_rng
rng = default_rng(12345)
random_array = rng.random(10)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [25]:
rng = default_rng(12345)
mean, stddev = 5, 1
random_normal = rng.normal(mean, stddev, size=10)
random_normal

array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669,
       4.25911535, 3.6322073 , 5.6488928 , 5.36105811, 3.04713694])

In [26]:
#Array operations
import numpy as np
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]

sales_array = np.array(sales)
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [27]:
sales_array + 2

array([[   2,    7,  157,    2,  520],
       [   2, 1829,  618,  319,  327]])

In [28]:
quantity = sales_array[0, :]
quantity

array([  0,   5, 155,   0, 518])

In [29]:
price = sales_array[1, :]
price

array([   0, 1827,  616,  317,  325])

In [30]:
quantity * price

array([     0,   9135,  95480,      0, 168350])

In [31]:
import numpy as np
prices  = np.array([5.99, 6.99, 22.99, 99.99, 4.99, 49.99])

In [32]:
total = prices + 5
total

array([ 10.99,  11.99,  27.99, 104.99,   9.99,  54.99])

In [33]:
import numpy as np


random_array = np.random.rand(12)

discount_pct = random_array[:6].reshape(6)   
pct_owed = 1 - discount_pct
final_owed = total + pct_owed
final_owed.round(2)

array([ 11.29,  12.67,  28.54, 105.98,  10.16,  55.05])

In [34]:
###filtering arrays

In [35]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [36]:
sales_array != 0

array([[False,  True,  True, False,  True],
       [False,  True,  True,  True,  True]])

In [37]:
sales_array[sales_array != 0]

array([   5,  155,  518, 1827,  616,  317,  325])

In [38]:
# multiple logical tests

In [39]:
sales_array[(sales_array > 100) & (sales_array < 500)]

array([155, 317, 325])

In [40]:
###PRO TIP: Store complex
#filtering criteria in a variable
#(known as a Boolean mask)

mask = (sales_array > 100) & (sales_array < 500)
sales_array[mask]

array([155, 317, 325])

In [41]:
##filter arrays based on values in other arrays

In [42]:
product_list = ['fruits', 'vegetable', 'cereal', 'dairy', 'eggs', 'meat','potatoes']
product_array = np.array(product_list)
product_array

array(['fruits', 'vegetable', 'cereal', 'dairy', 'eggs', 'meat',
       'potatoes'], dtype='<U9')

In [43]:
#product_array[sales_array > 0]

In [44]:
print(product_array.shape)
print(sales_array.shape)

(7,)
(2, 5)

In [45]:
sales_array.shape

(2, 5)

In [46]:
sales_array[1] = 5

In [47]:
sales_array

array([[  0,   5, 155,   0, 518],
       [  5,   5,   5,   5,   5]])

In [48]:
sales_array[sales_array == 0] = 25

In [49]:
sales_array

array([[ 25,   5, 155,  25, 518],
       [  5,   5,   5,   5,   5]])

In [50]:
inventory_list = [12, 102, 18, 0, 0]

In [51]:
inventory_array = np.array(inventory_list)

In [52]:
inventory_array

array([ 12, 102,  18,   0,   0])

In [53]:
np.where(inventory_array <= 0, 'out_of_stock', 'in_stock')

array(['in_stock', 'in_stock', 'in_stock', 'out_of_stock', 'out_of_stock'],
      dtype='<U12')

In [54]:
product_list = ['fruits', 'vegetable', 'cereal', 'dairy', 'eggs']
product_array = np.array(product_list)
product_array

array(['fruits', 'vegetable', 'cereal', 'dairy', 'eggs'], dtype='<U9')

In [55]:
np.where(inventory_array <= 0, 'out_of_stock', product_array)

array(['fruits', 'vegetable', 'cereal', 'out_of_stock', 'out_of_stock'],
      dtype='<U12')

In [56]:
sales_array

array([[ 25,   5, 155,  25, 518],
       [  5,   5,   5,   5,   5]])

In [57]:
print(f'The sum is: {sales_array.sum()}')
print(f'The min is: {sales_array.min()}')
print(f'The max is: {sales_array.max()}')
print(f'The mean is: {sales_array.mean()}')

The sum is: 753
The min is: 5
The max is: 518
The mean is: 75.3

In [58]:
print(f'The sum is aggregated across the rows: {sales_array.sum(axis=0)}')
print(f'The sum is aggregated across the columns: {sales_array.sum(axis=1)}')

The sum is aggregated across the rows: [ 30  10 160  30 523]
The sum is aggregated across the columns: [728  25]

In [59]:
np.unique(sales_array)

array([  5,  25, 155, 518])

In [60]:
np.sqrt(sales_array)

array([[ 5.        ,  2.23606798, 12.4498996 ,  5.        , 22.75961335],
       [ 2.23606798,  2.23606798,  2.23606798,  2.23606798,  2.23606798]])

In [61]:
sales_array.sort()
sales_array

array([[  5,  25,  25, 155, 518],
       [  5,   5,   5,   5,   5]])

In [62]:
sales_array.sort(axis=0)
sales_array

array([[  5,   5,   5,   5,   5],
       [  5,  25,  25, 155, 518]])

In [63]:
import pandas as pd
retail_df = pd.read_csv(r"C:\Users\TAJ\Desktop\python 101_\data\retail_2016_2017.csv").sample(1000, random_state=100)

In [64]:
retail_df

,id,date,store_nbr,family,sales,onpromotion
497061,2443005,2016-10-05,6,HOME AND KITCHEN I,31.000,0
562089,2508033,2016-11-11,30,AUTOMOTIVE,2.000,0
165783,2111727,2016-04-03,10,MEATS,278.173,0
531350,2477294,2016-10-25,18,HOME APPLIANCES,0.000,0
540362,2486306,2016-10-30,20,LAWN AND GARDEN,7.000,2
...,...,...,...,...,...,...
231385,2177329,2016-05-09,50,"LIQUOR,WINE,BEER",69.000,0
926789,2872733,2017-06-05,13,HOME APPLIANCES,0.000,0
513748,2459692,2016-10-15,24,BOOKS,6.000,0
72189,2018133,2016-02-10,34,HOME CARE,269.000,0
416915,2362859,2016-08-21,7,PET SUPPLIES,5.000,0

In [65]:
family_array = np.array(retail_df['family'])
family_array

array(['HOME AND KITCHEN I', 'AUTOMOTIVE', 'MEATS', 'HOME APPLIANCES',
       'LAWN AND GARDEN', 'PRODUCE', 'PREPARED FOODS', 'PRODUCE',
       'PREPARED FOODS', 'BEAUTY', 'EGGS', 'POULTRY', 'GROCERY II',
       'GROCERY I', 'CLEANING', 'POULTRY', 'BREAD/BAKERY', 'PET SUPPLIES',
       'HOME AND KITCHEN I', 'LAWN AND GARDEN', 'HOME AND KITCHEN I',
       'MEATS', 'HOME CARE', 'GROCERY I', 'PERSONAL CARE', 'BREAD/BAKERY',
       'HOME AND KITCHEN I', 'GROCERY II', 'EGGS',
       'SCHOOL AND OFFICE SUPPLIES', 'MAGAZINES', 'LADIESWEAR',
       'GROCERY I', 'BEAUTY', 'HOME APPLIANCES', 'CELEBRATION',
       'HARDWARE', 'MAGAZINES', 'MAGAZINES', 'CLEANING',
       'LIQUOR,WINE,BEER', 'MAGAZINES', 'SEAFOOD', 'BEAUTY',
       'CELEBRATION', 'PREPARED FOODS', 'HARDWARE', 'LAWN AND GARDEN',
       'PLAYERS AND ELECTRONICS', 'SCHOOL AND OFFICE SUPPLIES',
       'LAWN AND GARDEN', 'MEATS', 'BEAUTY', 'DAIRY', 'HOME APPLIANCES',
       'SEAFOOD', 'CLEANING', 'FROZEN FOODS', 'BEVERAGES', 'FROZEN FOODS',
       'HOME CARE', 'PERSONAL CARE', 'EGGS', 'BEVERAGES',
       'SCHOOL AND OFFICE SUPPLIES', 'HOME CARE', 'PERSONAL CARE',
       'MAGAZINES', 'DELI', 'LIQUOR,WINE,BEER',
       'SCHOOL AND OFFICE SUPPLIES', 'FROZEN FOODS', 'HOME AND KITCHEN I',
       'HOME AND KITCHEN II', 'PRODUCE', 'HOME CARE', 'CLEANING',
       'GROCERY II', 'LAWN AND GARDEN', 'POULTRY', 'LAWN AND GARDEN',
       'DELI', 'MEATS', 'CLEANING', 'PERSONAL CARE', 'CLEANING', 'MEATS',
       'PRODUCE', 'SEAFOOD', 'BREAD/BAKERY', 'LAWN AND GARDEN',
       'MAGAZINES', 'MEATS', 'FROZEN FOODS', 'PLAYERS AND ELECTRONICS',
       'DAIRY', 'PREPARED FOODS', 'FROZEN FOODS', 'BOOKS', 'MAGAZINES',
       'MAGAZINES', 'AUTOMOTIVE', 'BREAD/BAKERY', 'PREPARED FOODS',
       'BEVERAGES', 'SCHOOL AND OFFICE SUPPLIES', 'LAWN AND GARDEN',
       'HOME AND KITCHEN II', 'AUTOMOTIVE', 'MEATS', 'MAGAZINES',
       'BABY CARE', 'BABY CARE', 'MAGAZINES', 'CLEANING', 'EGGS',
       'HOME CARE', 'CLEANING', 'CELEBRATION', 'EGGS', 'PREPARED FOODS',
       'LADIESWEAR', 'GROCERY II', 'PLAYERS AND ELECTRONICS', 'MEATS',
       'SEAFOOD', 'PLAYERS AND ELECTRONICS', 'HOME CARE',
       'SCHOOL AND OFFICE SUPPLIES', 'POULTRY', 'SEAFOOD', 'BOOKS',
       'LINGERIE', 'BOOKS', 'PLAYERS AND ELECTRONICS', 'PREPARED FOODS',
       'LADIESWEAR', 'BEVERAGES', 'PERSONAL CARE', 'POULTRY', 'BOOKS',
       'MEATS', 'GROCERY II', 'MAGAZINES', 'CELEBRATION', 'MAGAZINES',
       'LADIESWEAR', 'GROCERY I', 'HARDWARE', 'BEVERAGES',
       'LIQUOR,WINE,BEER', 'MEATS', 'CELEBRATION', 'HOME AND KITCHEN II',
       'PREPARED FOODS', 'PET SUPPLIES', 'DAIRY', 'LAWN AND GARDEN',
       'HOME AND KITCHEN II', 'BOOKS', 'DAIRY', 'BABY CARE', 'BEVERAGES',
       'HOME AND KITCHEN II', 'HARDWARE', 'FROZEN FOODS',
       'PLAYERS AND ELECTRONICS', 'DELI', 'MAGAZINES', 'GROCERY I',
       'GROCERY I', 'MAGAZINES', 'DAIRY', 'GROCERY I', 'BABY CARE',
       'LAWN AND GARDEN', 'HOME AND KITCHEN I', 'LAWN AND GARDEN',
       'DAIRY', 'BOOKS', 'HARDWARE', 'PRODUCE', 'MAGAZINES', 'GROCERY I',
       'BEAUTY', 'EGGS', 'DAIRY', 'EGGS', 'LAWN AND GARDEN',
       'SCHOOL AND OFFICE SUPPLIES', 'EGGS', 'PET SUPPLIES', 'MAGAZINES',
       'GROCERY I', 'POULTRY', 'HOME AND KITCHEN I', 'HOME CARE',
       'PET SUPPLIES', 'BOOKS', 'PET SUPPLIES', 'BREAD/BAKERY',
       'HOME CARE', 'HARDWARE', 'BEAUTY', 'PET SUPPLIES', 'GROCERY II',
       'BABY CARE', 'SCHOOL AND OFFICE SUPPLIES', 'DELI', 'PRODUCE',
       'PREPARED FOODS', 'PRODUCE', 'LADIESWEAR', 'POULTRY',
       'PET SUPPLIES', 'LADIESWEAR', 'LIQUOR,WINE,BEER', 'CLEANING',
       'LIQUOR,WINE,BEER', 'LADIESWEAR', 'LAWN AND GARDEN',
       'PLAYERS AND ELECTRONICS', 'BABY CARE', 'PET SUPPLIES',
       'LIQUOR,WINE,BEER', 'FROZEN FOODS', 'GROCERY II', 'CELEBRATION',
       'HOME AND KITCHEN I', 'DAIRY', 'CELEBRATION', 'PREPARED FOODS',
       'SEAFOOD', 'HOME APPLIANCES', 'PRODUCE', 'PREPARED FOODS',
       'LAWN AND GARDEN', 'POULTRY', 'POULTRY', 'HOME AND KITCHEN II',
       'GROCERY I', 'PET SUPPLIES', 'PLAYERS AND ELECTRONICS',
       'AUTOMOTIVE', 'BABY CARE', 'PLAYERS AND ELECTRONICS',
       'HOME AND KITCHEN II', 'FROZEN FOODS', 'EGGS', 'DELI',
       'LADIESWEAR', 'LINGERIE', 'CELEBRATION', 'GROCERY II',
       'PREPARED FOODS', 'CLEANING', 'HOME CARE', 'HARDWARE', 'GROCERY I',
       'PLAYERS AND ELECTRONICS', 'AUTOMOTIVE', 'MEATS', 'SEAFOOD',
       'DELI', 'BEVERAGES', 'GROCERY I', 'PET SUPPLIES', 'GROCERY I',
       'PRODUCE', 'BOOKS', 'PET SUPPLIES', 'PERSONAL CARE', 'AUTOMOTIVE',
       'HOME AND KITCHEN II', 'AUTOMOTIVE', 'SCHOOL AND OFFICE SUPPLIES',
       'AUTOMOTIVE', 'PERSONAL CARE', 'LINGERIE', 'GROCERY II', 'EGGS',
       'LIQUOR,WINE,BEER', 'DELI', 'PREPARED FOODS', 'SEAFOOD',
       'LAWN AND GARDEN', 'SCHOOL AND OFFICE SUPPLIES', 'POULTRY',
       'HOME APPLIANCES', 'SCHOOL AND OFFICE SUPPLIES', 'BABY CARE',
       'PREPARED FOODS', 'GROCERY II', 'MAGAZINES', 'LIQUOR,WINE,BEER',
       'BREAD/BAKERY', 'HOME CARE', 'AUTOMOTIVE', 'POULTRY', 'BEVERAGES',
       'BOOKS', 'SEAFOOD', 'HOME AND KITCHEN I', 'HOME AND KITCHEN II',
       'AUTOMOTIVE', 'CLEANING', 'FROZEN FOODS', 'AUTOMOTIVE',
       'CELEBRATION', 'BREAD/BAKERY', 'EGGS', 'LIQUOR,WINE,BEER', 'EGGS',
       'CELEBRATION', 'SEAFOOD', 'GROCERY II', 'FROZEN FOODS',
       'SCHOOL AND OFFICE SUPPLIES', 'HOME AND KITCHEN II',
       'PLAYERS AND ELECTRONICS', 'DAIRY', 'BEAUTY', 'LINGERIE',
       'GROCERY I', 'PET SUPPLIES', 'POULTRY', 'PERSONAL CARE',
       'PLAYERS AND ELECTRONICS', 'DAIRY', 'PREPARED FOODS',
       'PERSONAL CARE', 'LINGERIE', 'DELI', 'PERSONAL CARE', 'HOME CARE',
       'MAGAZINES', 'HOME AND KITCHEN I', 'FROZEN FOODS', 'BEVERAGES',
       'PREPARED FOODS', 'LINGERIE', 'EGGS', 'GROCERY II',
       'PLAYERS AND ELECTRONICS', 'POULTRY', 'MAGAZINES', 'FROZEN FOODS',
       'MAGAZINES', 'CLEANING', 'HOME AND KITCHEN II', 'GROCERY I',
       'BREAD/BAKERY', 'PET SUPPLIES', 'LAWN AND GARDEN',
       'LIQUOR,WINE,BEER', 'EGGS', 'MAGAZINES', 'HOME CARE', 'GROCERY I',
       'HOME CARE', 'AUTOMOTIVE', 'FROZEN FOODS', 'MEATS', 'SEAFOOD',
       'HOME AND KITCHEN I', 'BEVERAGES', 'PET SUPPLIES', 'DELI',
       'CLEANING', 'HOME AND KITCHEN I', 'BEVERAGES', 'HOME CARE',
       'PREPARED FOODS', 'SEAFOOD', 'HOME CARE', 'DELI', 'HARDWARE',
       'DAIRY', 'EGGS', 'HOME AND KITCHEN I', 'CLEANING', 'EGGS',
       'AUTOMOTIVE', 'DAIRY', 'POULTRY', 'HOME AND KITCHEN I',
       'MAGAZINES', 'FROZEN FOODS', 'SEAFOOD', 'GROCERY II', 'LINGERIE',
       'LAWN AND GARDEN', 'FROZEN FOODS', 'MEATS', 'BABY CARE',
       'AUTOMOTIVE', 'LIQUOR,WINE,BEER', 'SCHOOL AND OFFICE SUPPLIES',
       'DAIRY', 'EGGS', 'BEVERAGES', 'HOME CARE', 'LAWN AND GARDEN',
       'PREPARED FOODS', 'DELI', 'MAGAZINES', 'HARDWARE',
       'HOME APPLIANCES', 'DELI', 'LIQUOR,WINE,BEER', 'MAGAZINES',
       'LIQUOR,WINE,BEER', 'HOME AND KITCHEN I', 'DELI', 'CLEANING',
       'HOME CARE', 'BEAUTY', 'MEATS', 'LINGERIE', 'BEVERAGES',
       'HOME AND KITCHEN I', 'DELI', 'CLEANING', 'BABY CARE',
       'BREAD/BAKERY', 'AUTOMOTIVE', 'HOME CARE', 'LIQUOR,WINE,BEER',
       'AUTOMOTIVE', 'POULTRY', 'MAGAZINES', 'HOME AND KITCHEN I',
       'FROZEN FOODS', 'BOOKS', 'GROCERY I', 'HOME CARE', 'DELI',
       'AUTOMOTIVE', 'FROZEN FOODS', 'HOME AND KITCHEN I', 'BOOKS',
       'BOOKS', 'PRODUCE', 'MAGAZINES', 'PLAYERS AND ELECTRONICS',
       'PLAYERS AND ELECTRONICS', 'SEAFOOD', 'LIQUOR,WINE,BEER',
       'SEAFOOD', 'BEAUTY', 'CELEBRATION', 'HOME CARE',
       'LIQUOR,WINE,BEER', 'LAWN AND GARDEN', 'MAGAZINES', 'LINGERIE',
       'DAIRY', 'AUTOMOTIVE', 'BEVERAGES', 'PET SUPPLIES', 'BABY CARE',
       'DAIRY', 'LIQUOR,WINE,BEER', 'GROCERY I', 'LAWN AND GARDEN',
       'CELEBRATION', 'EGGS', 'BOOKS', 'CLEANING', 'HOME AND KITCHEN II',
       'GROCERY I', 'BABY CARE', 'PLAYERS AND ELECTRONICS', 'MAGAZINES',
       'LADIESWEAR', 'AUTOMOTIVE', 'DELI', 'SEAFOOD',
       'PLAYERS AND ELECTRONICS', 'POULTRY', 'MAGAZINES', 'CELEBRATION',
       'PRODUCE', 'FROZEN FOODS', 'LADIESWEAR', 'PLAYERS AND ELECTRONICS',
       'AUTOMOTIVE', 'BEVERAGES', 'CELEBRATION', 'BEAUTY', 'HOME CARE',
       'EGGS', 'FROZEN FOODS', 'FROZEN FOODS', 'BEVERAGES', 'GROCERY I',
       'BEAUTY', 'HOME APPLIANCES', 'PET SUPPLIES', 'MEATS',
       'LIQUOR,WINE,BEER', 'HOME AND KITCHEN II', 'DAIRY',
       'PREPARED FOODS', 'GROCERY II', 'BEAUTY', 'GROCERY II',
       'LIQUOR,WINE,BEER', 'HOME AND KITCHEN II', 'BEVERAGES',
       'HOME CARE', 'HOME CARE', 'MAGAZINES', 'PERSONAL CARE',
       'LIQUOR,WINE,BEER', 'SCHOOL AND OFFICE SUPPLIES',
       'HOME AND KITCHEN II', 'FROZEN FOODS', 'FROZEN FOODS', 'EGGS',
       'FROZEN FOODS', 'HOME CARE', 'SEAFOOD', 'LINGERIE',
       'HOME APPLIANCES', 'BREAD/BAKERY', 'BABY CARE', 'BEAUTY',
       'FROZEN FOODS', 'GROCERY I', 'PET SUPPLIES', 'DAIRY',
       'HOME AND KITCHEN I', 'DELI', 'PREPARED FOODS', 'HARDWARE',
       'CELEBRATION', 'MAGAZINES', 'HOME CARE', 'PREPARED FOODS',
       'MAGAZINES', 'HOME AND KITCHEN I', 'EGGS', 'HOME AND KITCHEN I',
       'BEVERAGES', 'SEAFOOD', 'PLAYERS AND ELECTRONICS', 'HARDWARE',
       'PLAYERS AND ELECTRONICS', 'LADIESWEAR', 'PET SUPPLIES',
       'GROCERY II', 'PET SUPPLIES', 'DELI', 'EGGS',
       'PLAYERS AND ELECTRONICS', 'PRODUCE', 'DAIRY',
       'PLAYERS AND ELECTRONICS', 'LAWN AND GARDEN', 'CELEBRATION',
       'MEATS', 'HARDWARE', 'HOME CARE', 'LIQUOR,WINE,BEER', 'BABY CARE',
       'BABY CARE', 'LINGERIE', 'PERSONAL CARE', 'BOOKS',
       'LAWN AND GARDEN', 'BREAD/BAKERY', 'SCHOOL AND OFFICE SUPPLIES',
       'PLAYERS AND ELECTRONICS', 'CELEBRATION', 'GROCERY II',
       'CELEBRATION', 'SEAFOOD', 'PRODUCE', 'MEATS', 'LADIESWEAR',
       'GROCERY II', 'BREAD/BAKERY', 'EGGS', 'HOME AND KITCHEN I',
       'GROCERY I', 'BEAUTY', 'PLAYERS AND ELECTRONICS', 'LINGERIE',
       'CLEANING', 'PLAYERS AND ELECTRONICS', 'HOME AND KITCHEN I',
       'EGGS', 'BEAUTY', 'FROZEN FOODS', 'EGGS', 'HOME APPLIANCES',
       'LIQUOR,WINE,BEER', 'EGGS', 'LIQUOR,WINE,BEER', 'HOME APPLIANCES',
       'PRODUCE', 'HARDWARE', 'PERSONAL CARE', 'HOME AND KITCHEN I',
       'HARDWARE', 'HOME AND KITCHEN I', 'LAWN AND GARDEN',
       'BREAD/BAKERY', 'SEAFOOD', 'AUTOMOTIVE', 'HOME APPLIANCES',
       'SCHOOL AND OFFICE SUPPLIES', 'PREPARED FOODS', 'PRODUCE',
       'SCHOOL AND OFFICE SUPPLIES', 'PREPARED FOODS', 'EGGS',
       'HOME CARE', 'CLEANING', 'DAIRY', 'GROCERY I', 'HARDWARE',
       'BREAD/BAKERY', 'LAWN AND GARDEN', 'HOME APPLIANCES',
       'PLAYERS AND ELECTRONICS', 'HOME AND KITCHEN I', 'FROZEN FOODS',
       'CELEBRATION', 'SCHOOL AND OFFICE SUPPLIES', 'BOOKS',
       'PET SUPPLIES', 'BEAUTY', 'MEATS', 'LIQUOR,WINE,BEER',
       'LIQUOR,WINE,BEER', 'HARDWARE', 'MEATS', 'CELEBRATION', 'CLEANING',
       'CLEANING', 'BEAUTY', 'LINGERIE', 'LIQUOR,WINE,BEER', 'LINGERIE',
       'MEATS', 'BEVERAGES', 'BREAD/BAKERY', 'CELEBRATION',
       'HOME AND KITCHEN I', 'PREPARED FOODS', 'FROZEN FOODS', 'MEATS',
       'MAGAZINES', 'BEVERAGES', 'GROCERY I', 'BREAD/BAKERY',
       'HOME APPLIANCES', 'DELI', 'DAIRY', 'EGGS', 'HARDWARE',
       'SCHOOL AND OFFICE SUPPLIES', 'HOME AND KITCHEN II', 'CLEANING',
       'BABY CARE', 'CLEANING', 'EGGS', 'MAGAZINES', 'CELEBRATION',
       'LIQUOR,WINE,BEER', 'CLEANING', 'PREPARED FOODS',
       'HOME AND KITCHEN I', 'HARDWARE', 'HOME AND KITCHEN I', 'EGGS',
       'SCHOOL AND OFFICE SUPPLIES', 'BEVERAGES', 'LAWN AND GARDEN',
       'BEAUTY', 'MAGAZINES', 'PERSONAL CARE', 'PLAYERS AND ELECTRONICS',
       'PERSONAL CARE', 'MEATS', 'DAIRY', 'PLAYERS AND ELECTRONICS',
       'FROZEN FOODS', 'MEATS', 'SCHOOL AND OFFICE SUPPLIES', 'MAGAZINES',
       'PET SUPPLIES', 'LADIESWEAR', 'LIQUOR,WINE,BEER', 'PET SUPPLIES',
       'HOME APPLIANCES', 'HOME AND KITCHEN II', 'MAGAZINES',
       'CELEBRATION', 'BEAUTY', 'BEVERAGES', 'MEATS', 'DAIRY',
       'LIQUOR,WINE,BEER', 'PERSONAL CARE', 'EGGS', 'MAGAZINES',
       'SEAFOOD', 'MEATS', 'HOME AND KITCHEN II', 'HOME AND KITCHEN II',
       'SCHOOL AND OFFICE SUPPLIES', 'HOME CARE', 'AUTOMOTIVE',
       'HOME AND KITCHEN II', 'PET SUPPLIES', 'GROCERY I',
       'HOME APPLIANCES', 'DELI', 'LIQUOR,WINE,BEER', 'PREPARED FOODS',
       'LIQUOR,WINE,BEER', 'CLEANING', 'BREAD/BAKERY', 'HARDWARE',
       'POULTRY', 'GROCERY I', 'PREPARED FOODS', 'SEAFOOD', 'CELEBRATION',
       'BEAUTY', 'LINGERIE', 'MAGAZINES', 'AUTOMOTIVE', 'LINGERIE',
       'BEAUTY', 'BEAUTY', 'PREPARED FOODS', 'EGGS', 'GROCERY I',
       'CLEANING', 'SEAFOOD', 'CELEBRATION', 'HOME AND KITCHEN II',
       'BREAD/BAKERY', 'LADIESWEAR', 'CELEBRATION', 'PREPARED FOODS',
       'HOME AND KITCHEN I', 'PRODUCE', 'DAIRY',
       'SCHOOL AND OFFICE SUPPLIES', 'MEATS', 'BEAUTY', 'BEAUTY',
       'CELEBRATION', 'BOOKS', 'CELEBRATION', 'GROCERY II',
       'PET SUPPLIES', 'POULTRY', 'GROCERY II', 'FROZEN FOODS',
       'AUTOMOTIVE', 'POULTRY', 'GROCERY I', 'HOME AND KITCHEN II',
       'PERSONAL CARE', 'BREAD/BAKERY', 'LIQUOR,WINE,BEER', 'MAGAZINES',
       'LAWN AND GARDEN', 'LADIESWEAR', 'PERSONAL CARE',
       'LIQUOR,WINE,BEER', 'PERSONAL CARE', 'AUTOMOTIVE', 'LINGERIE',
       'LIQUOR,WINE,BEER', 'POULTRY', 'HOME AND KITCHEN I',
       'FROZEN FOODS', 'DELI', 'BEAUTY', 'HOME CARE', 'PERSONAL CARE',
       'FROZEN FOODS', 'GROCERY II', 'BOOKS', 'FROZEN FOODS',
       'HOME APPLIANCES', 'PREPARED FOODS', 'MAGAZINES', 'PERSONAL CARE',
       'GROCERY I', 'PET SUPPLIES', 'CLEANING', 'MEATS', 'SEAFOOD',
       'BOOKS', 'DAIRY', 'BOOKS', 'POULTRY', 'LAWN AND GARDEN',
       'AUTOMOTIVE', 'BREAD/BAKERY', 'AUTOMOTIVE', 'DAIRY',
       'PREPARED FOODS', 'PRODUCE', 'AUTOMOTIVE', 'GROCERY I', 'DAIRY',
       'MAGAZINES', 'PERSONAL CARE', 'LINGERIE', 'PET SUPPLIES',
       'HOME APPLIANCES', 'BEVERAGES', 'BOOKS', 'LADIESWEAR', 'BEVERAGES',
       'AUTOMOTIVE', 'SEAFOOD', 'HOME AND KITCHEN II', 'BEAUTY',
       'PREPARED FOODS', 'AUTOMOTIVE', 'SEAFOOD', 'LADIESWEAR',
       'LADIESWEAR', 'HARDWARE', 'LINGERIE', 'LAWN AND GARDEN',
       'LINGERIE', 'PRODUCE', 'POULTRY', 'HARDWARE', 'CLEANING',
       'BABY CARE', 'HARDWARE', 'DAIRY', 'MEATS', 'PET SUPPLIES',
       'GROCERY I', 'HOME AND KITCHEN I', 'HOME AND KITCHEN II',
       'GROCERY I', 'PERSONAL CARE', 'EGGS', 'HOME AND KITCHEN I',
       'GROCERY I', 'PRODUCE', 'MAGAZINES', 'HOME APPLIANCES', 'CLEANING',
       'PLAYERS AND ELECTRONICS', 'MAGAZINES', 'GROCERY II',
       'CELEBRATION', 'PRODUCE', 'PRODUCE', 'BEVERAGES', 'LADIESWEAR',
       'HOME APPLIANCES', 'HOME AND KITCHEN I', 'BEAUTY', 'PRODUCE',
       'SEAFOOD', 'GROCERY II', 'LAWN AND GARDEN', 'CELEBRATION',
       'SCHOOL AND OFFICE SUPPLIES', 'EGGS', 'PREPARED FOODS',
       'MAGAZINES', 'BEAUTY', 'BREAD/BAKERY', 'MAGAZINES', 'CELEBRATION',
       'DELI', 'PRODUCE', 'DELI', 'PET SUPPLIES', 'GROCERY I',
       'LAWN AND GARDEN', 'HOME AND KITCHEN I', 'AUTOMOTIVE', 'DELI',
       'HARDWARE', 'LAWN AND GARDEN', 'HOME AND KITCHEN II', 'LINGERIE',
       'GROCERY II', 'HOME AND KITCHEN II', 'PET SUPPLIES', 'DELI',
       'AUTOMOTIVE', 'BEVERAGES', 'DAIRY', 'HOME AND KITCHEN II',
       'BREAD/BAKERY', 'PLAYERS AND ELECTRONICS', 'DAIRY', 'DAIRY',
       'LINGERIE', 'MEATS', 'GROCERY I', 'PRODUCE', 'BEVERAGES', 'MEATS',
       'PLAYERS AND ELECTRONICS', 'CLEANING', 'HARDWARE', 'MAGAZINES',
       'PREPARED FOODS', 'HOME AND KITCHEN II', 'CLEANING',
       'SCHOOL AND OFFICE SUPPLIES', 'HOME AND KITCHEN I', 'FROZEN FOODS',
       'BOOKS', 'PLAYERS AND ELECTRONICS', 'POULTRY', 'GROCERY II',
       'SEAFOOD', 'LIQUOR,WINE,BEER', 'CLEANING', 'FROZEN FOODS',
       'PLAYERS AND ELECTRONICS', 'POULTRY', 'DELI', 'LINGERIE',
       'HOME CARE', 'SEAFOOD', 'HOME CARE', 'MAGAZINES',
       'HOME AND KITCHEN II', 'HOME AND KITCHEN II', 'PET SUPPLIES',
       'LAWN AND GARDEN', 'GROCERY I', 'MAGAZINES', 'EGGS', 'LINGERIE',
       'BABY CARE', 'LAWN AND GARDEN', 'BABY CARE', 'EGGS', 'BABY CARE',
       'DELI', 'BEAUTY', 'MEATS', 'MEATS', 'PET SUPPLIES', 'LADIESWEAR',
       'HOME AND KITCHEN II', 'MEATS', 'SCHOOL AND OFFICE SUPPLIES',
       'CELEBRATION', 'LAWN AND GARDEN', 'LAWN AND GARDEN', 'DAIRY',
       'FROZEN FOODS', 'PERSONAL CARE', 'POULTRY',
       'PLAYERS AND ELECTRONICS', 'BOOKS', 'BEAUTY', 'MEATS',
       'HOME AND KITCHEN I', 'SEAFOOD', 'HOME AND KITCHEN I',
       'PERSONAL CARE', 'PRODUCE', 'BEVERAGES', 'HOME APPLIANCES',
       'BABY CARE', 'PERSONAL CARE', 'HOME CARE', 'LIQUOR,WINE,BEER',
       'LAWN AND GARDEN', 'BEAUTY', 'SEAFOOD', 'DELI', 'AUTOMOTIVE',
       'BEAUTY', 'SCHOOL AND OFFICE SUPPLIES', 'BABY CARE', 'POULTRY',
       'HARDWARE', 'PERSONAL CARE', 'LIQUOR,WINE,BEER',
       'LIQUOR,WINE,BEER', 'HOME APPLIANCES', 'BOOKS', 'HOME CARE',
       'PET SUPPLIES'], dtype=object)

In [66]:
sales_array = np.array(retail_df['sales'])
sales_array

array([3.10000000e+01, 2.00000000e+00, 2.78173000e+02, 0.00000000e+00,
       7.00000000e+00, 1.04171250e+04, 5.80670000e+01, 8.71078900e+03,
       7.68740000e+01, 5.00000000e+00, 2.91000000e+02, 9.08394000e+02,
       2.30000000e+01, 8.04500000e+03, 2.16000000e+03, 1.15283005e+02,
       0.00000000e+00, 6.00000000e+00, 9.00000000e+00, 2.80000000e+01,
       1.50000000e+01, 6.06000000e+01, 4.09000000e+02, 4.36400000e+03,
       1.23000000e+02, 5.49482000e+02, 1.10000000e+01, 1.70000000e+01,
       3.40000000e+01, 2.00000000e+00, 2.10000000e+01, 6.00000000e+01,
       1.43720000e+04, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 2.00000000e+00, 1.10000000e+01, 1.24900000e+03,
       3.10000000e+02, 3.00000000e+00, 2.55320000e+01, 2.00000000e+00,
       8.00000000e+00, 6.28050000e+01, 0.00000000e+00, 0.00000000e+00,
       1.40000000e+01, 0.00000000e+00, 5.00000000e+00, 5.22984000e+02,
       5.00000000e+00, 4.69000000e+02, 0.00000000e+00, 2.17320000e+01,
       7.96000000e+02, 5.23965000e+02, 1.41680000e+04, 1.49968000e+02,
       1.97000000e+02, 1.61000000e+02, 5.50000000e+02, 1.03600000e+03,
       0.00000000e+00, 2.79000000e+02, 4.80000000e+02, 1.00000000e+00,
       8.50000000e+01, 3.90000000e+01, 0.00000000e+00, 2.63227000e+02,
       1.00000000e+01, 8.90000000e+01, 1.50481600e+03, 1.84000000e+02,
       4.43000000e+02, 1.10000000e+01, 9.00000000e+00, 8.78740000e+01,
       1.00000000e+00, 0.00000000e+00, 2.05846010e+02, 6.72000000e+02,
       5.16000000e+02, 8.72000000e+02, 1.87528000e+02, 1.24918400e+03,
       0.00000000e+00, 6.12493000e+02, 3.00000000e+00, 3.00000000e+00,
       1.56505000e+02, 6.66421000e+02, 0.00000000e+00, 3.23200000e+03,
       3.31900000e+01, 1.70000000e+01, 0.00000000e+00, 3.00000000e+00,
       1.10000000e+01, 2.40000000e+01, 5.91000000e+02, 2.90000000e+01,
       1.56000000e+03, 0.00000000e+00, 1.30000000e+01, 4.00000000e+01,
       1.20000000e+01, 3.48690000e+02, 6.00000000e+00, 0.00000000e+00,
       5.00000000e+00, 0.00000000e+00, 1.36300000e+03, 4.40000000e+01,
       3.40000000e+02, 1.55700000e+03, 3.00000000e+00, 4.66000000e+02,
       3.70000000e+01, 0.00000000e+00, 6.00000000e+00, 1.30000000e+01,
       1.15454000e+02, 5.00000000e+00, 1.30000000e+01, 1.96000000e+02,
       0.00000000e+00, 3.51201000e+02, 1.10000000e+01, 0.00000000e+00,
       2.00000000e+00, 0.00000000e+00, 2.00000000e+00, 3.32082000e+02,
       1.00000000e+00, 8.39700000e+03, 3.93000000e+02, 6.49917000e+02,
       0.00000000e+00, 2.95044000e+02, 2.10000000e+01, 0.00000000e+00,
       0.00000000e+00, 1.30000000e+01, 1.70000000e+01, 3.44300000e+03,
       0.00000000e+00, 1.27940000e+04, 1.46000000e+02, 2.64514000e+02,
       1.00000000e+00, 3.20000000e+01, 1.20766000e+02, 2.00000000e+00,
       2.49400000e+03, 0.00000000e+00, 1.54000000e+02, 0.00000000e+00,
       0.00000000e+00, 2.00000000e+00, 7.66800000e+03, 2.70000000e+01,
       5.00000000e+00, 8.20000000e+01, 8.00000000e+00, 2.57250000e+02,
       1.00000000e+00, 1.03003130e+04, 2.35300000e+03, 1.00000000e+00,
       5.05000000e+02, 6.43612800e+03, 0.00000000e+00, 1.20000000e+01,
       3.70000000e+01, 0.00000000e+00, 7.31000000e+02, 0.00000000e+00,
       0.00000000e+00, 1.92158900e+03, 6.00000000e+00, 4.91583500e+03,
       1.00000000e+00, 1.49000000e+02, 3.40000000e+02, 8.10000000e+01,
       7.00000000e+00, 3.00000000e+00, 4.70000000e+01, 5.00000000e+00,
       1.60000000e+01, 3.13291000e+03, 2.83534000e+02, 1.70000000e+01,
       3.05000000e+02, 2.70000000e+01, 0.00000000e+00, 3.00000000e+00,
       3.17000000e+02, 6.15000000e+02, 9.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.50000000e+01, 0.00000000e+00, 0.00000000e+00,
       2.06987000e+02, 7.25717400e+03, 8.05310000e+01, 1.41647400e+03,
       2.50000000e+01, 7.31230000e+01, 2.00000000e+00, 0.00000000e+00,
       5.20000000e+01, 1.17200000e+03, 1.03000000e+02, 2.00000000e+00,
       6.60000000e+01, 0.00000000e+00, 0.00000000e+00, 8.00000000e+00,
       4.80000000e+01, 0.00000000e+00, 1.50000000e+01, 2.20000000e+01,
       2.10000000e+01, 5.54000000e+02, 1.10000000e+01, 9.80000000e+01,
       4.00000000e+00, 0.00000000e+00, 2.81028300e+03, 3.00000000e+01,
       5.00000000e+00, 3.38461000e+02, 3.77428000e+02, 6.70000000e+01,
       0.00000000e+00, 1.00000000e+00, 2.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.20000000e+01, 5.00000000e+00, 2.06165000e+02,
       2.49000000e+02, 1.37741000e+02, 0.00000000e+00, 2.40000000e+01,
       1.90000000e+01, 7.30000000e+01, 7.00000000e+00, 1.24000000e+03,
       6.12000000e+02, 1.00000000e+00, 1.28450000e+04, 1.00000000e+00,
       1.10000000e+01, 2.71225000e+02, 1.00000000e+00, 1.95792000e+02,
       4.95600000e+03, 1.21310000e+04, 4.00000000e+01, 8.38300000e+03,
       2.04990400e+03, 0.00000000e+00, 3.00000000e+00, 6.20000000e+01,
       8.00000000e+00, 1.50000000e+01, 9.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 9.60000000e+01, 1.90000000e+01, 5.00000000e+00,
       5.50000000e+01, 1.62000000e+02, 1.63819990e+02, 8.56880000e+01,
       1.10000000e+01, 2.20000000e+01, 0.00000000e+00, 1.78543600e+03,
       1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.10997000e+02,
       6.00000000e+00, 1.00000000e+01, 7.00000000e+01, 4.62000000e+02,
       2.43000000e+02, 1.20000000e+01, 1.98408000e+02, 6.39400000e+03,
       0.00000000e+00, 7.27600000e+00, 1.30000000e+01, 1.30000000e+01,
       1.30000000e+01, 8.15000000e+02, 2.13408000e+02, 1.10000000e+01,
       2.50000000e+01, 7.36000000e+02, 8.40000000e+01, 2.60000000e+02,
       4.96000000e+02, 8.00000000e+00, 5.00000000e+00, 0.00000000e+00,
       6.50000000e+01, 0.00000000e+00, 2.00000000e+01, 2.00000000e+00,
       1.23800000e+03, 4.00000000e+00, 1.70000000e+01, 3.29118000e+03,
       1.70000000e+01, 6.86210000e+01, 2.49000000e+02, 3.00000000e+00,
       2.92000000e+02, 9.81380000e+01, 2.73000000e+02, 4.00000000e+00,
       2.59966000e+02, 3.20000000e+02, 2.43000000e+02, 1.00000000e+00,
       4.70000000e+01, 7.15769960e+01, 1.19700000e+03, 7.10000000e+01,
       1.90000000e+01, 4.90000000e+01, 0.00000000e+00, 3.50000000e+01,
       4.87401000e+02, 1.50000000e+01, 7.30000000e+01, 2.00000000e+00,
       1.12200000e+03, 8.60000000e+01, 6.20800000e+03, 1.58046700e+03,
       1.00000000e+00, 6.00000000e+00, 4.40000000e+01, 5.71000000e+02,
       2.10000000e+01, 2.34000000e+02, 2.32000000e+03, 2.41000000e+02,
       2.00000000e+00, 2.16000000e+02, 5.78382000e+02, 8.69230040e+01,
       2.00000000e+00, 1.85600000e+03, 2.00000000e+00, 4.88582000e+02,
       1.07800000e+03, 2.70000000e+01, 3.24900000e+03, 2.73000000e+02,
       9.10000000e+01, 0.00000000e+00, 2.00000000e+02, 8.17542000e+02,
       0.00000000e+00, 4.65000000e+02, 2.75000000e+02, 1.60000000e+01,
       7.15000000e+02, 6.40000000e+01, 7.00000000e+00, 0.00000000e+00,
       1.19201300e+03, 9.00000000e+00, 1.00000000e+00, 1.38991000e+02,
       3.44400000e+00, 1.40000000e+02, 9.00000000e+00, 1.90000000e+01,
       4.90000000e+01, 1.12722000e+02, 0.00000000e+00, 7.00000000e+00,
       3.49000000e+02, 0.00000000e+00, 1.10000000e+03, 1.12000000e+02,
       1.44600000e+03, 1.82000000e+02, 0.00000000e+00, 3.81350000e+01,
       3.56703000e+02, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       2.70134000e+02, 9.30000000e+01, 1.00000000e+01, 4.80000000e+01,
       6.60000000e+01, 1.42045000e+02, 1.14000000e+03, 1.77000000e+02,
       9.00000000e+00, 1.89206000e+02, 6.00000000e+00, 2.41800000e+03,
       1.20000000e+01, 1.41740000e+02, 1.80300000e+03, 0.00000000e+00,
       1.16000000e+02, 5.00000000e+00, 1.74000000e+02, 4.00000000e+01,
       7.00000000e+00, 1.43273000e+02, 0.00000000e+00, 2.10000000e+01,
       2.03000000e+02, 0.00000000e+00, 3.05027100e+03, 1.73000000e+02,
       4.95000000e+02, 3.00000000e+00, 3.92849000e+02, 3.10000000e+01,
       0.00000000e+00, 0.00000000e+00, 1.83336000e+02, 8.00000000e+00,
       8.00000000e+00, 1.60000000e+01, 5.96170000e+01, 2.20000000e+01,
       1.77620000e+01, 5.00000000e+00, 2.90000000e+01, 3.84000000e+02,
       2.90000000e+01, 0.00000000e+00, 1.00000000e+00, 5.00000000e+00,
       1.03500000e+03, 3.00000000e+00, 4.83300000e+03, 0.00000000e+00,
       1.00000000e+00, 8.10000000e+02, 6.50000000e+01, 1.29940000e+04,
       1.60000000e+01, 9.00000000e+00, 1.04000000e+02, 0.00000000e+00,
       1.19100000e+03, 8.00000000e+00, 5.72500000e+03, 0.00000000e+00,
       6.40000000e+01, 2.70000000e+01, 6.00000000e+00, 3.00000000e+00,
       3.11334000e+02, 2.70760000e+01, 6.00000000e+00, 0.00000000e+00,
       7.00000000e+00, 2.00000000e+00, 7.29332900e+03, 8.69500000e+01,
       8.00000000e+00, 7.00000000e+00, 9.00000000e+00, 9.84000000e+02,
       1.00000000e+00, 1.00000000e+00, 2.17000000e+02, 1.51000000e+02,
       4.39454000e+02, 2.08125000e+02, 2.04900000e+03, 3.95903000e+03,
       2.00000000e+00, 0.00000000e+00, 3.00000000e+00, 6.31250000e+01,
       5.00000000e+00, 1.40000000e+01, 3.84000000e+02, 1.59340000e+02,
       6.00000000e+00, 1.00000000e+00, 2.90000000e+01, 0.00000000e+00,
       1.40000000e+01, 1.18100000e+03, 4.64000000e+02, 2.21000000e+02,
       2.70000000e+01, 2.13000000e+02, 6.00000000e+01, 0.00000000e+00,
       1.00000000e+01, 2.30000000e+01, 6.20000000e+01, 5.70000000e+01,
       8.46110000e+01, 2.61000000e+02, 1.31180000e+01, 1.00000000e+00,
       0.00000000e+00, 5.29993000e+02, 1.00000000e+00, 2.00000000e+00,
       1.41000000e+02, 2.86300000e+03, 2.00000000e+01, 1.48400000e+03,
       4.20000000e+01, 1.42000000e+02, 8.04950000e+01, 2.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.18000000e+02, 6.00000000e+01,
       2.00000000e+00, 0.00000000e+00, 5.88000000e+02, 1.20000000e+01,
       3.19300000e+03, 0.00000000e+00, 6.00000000e+00, 1.00000000e+00,
       1.70000000e+01, 1.00000000e+01, 1.30000000e+01, 5.00000000e+00,
       3.00000000e+00, 5.10000000e+02, 3.14000000e+02, 1.00000000e+00,
       7.64423600e+03, 1.02300000e+03, 3.00000000e+00, 6.00000000e+00,
       2.00000000e+00, 1.33508000e+02, 4.00000000e+00, 4.51000000e+02,
       3.40000000e+01, 0.00000000e+00, 1.00000000e+00, 5.00000000e+00,
       2.72000000e+02, 0.00000000e+00, 3.00000000e+00, 9.01000000e+02,
       0.00000000e+00, 1.00000000e+01, 4.40000000e+01, 1.50000000e+01,
       9.00000000e+00, 8.99800000e+00, 1.36399000e+03, 1.89471000e+02,
       0.00000000e+00, 4.00000000e+00, 8.12000000e+02, 1.17000000e+02,
       6.50000000e+01, 1.36800000e+03, 7.00000000e+00, 1.20000000e+01,
       1.60000000e+01, 1.87000000e+03, 2.00000000e+00, 4.60000000e+01,
       1.44000000e+02, 1.60000000e+01, 4.56149980e+01, 9.30000000e+01,
       1.00000000e+00, 2.10000000e+01, 2.46000000e+02, 7.50000000e+01,
       0.00000000e+00, 2.89345000e+02, 2.00000000e+00, 8.00000000e+02,
       2.00000000e+01, 0.00000000e+00, 3.20000000e+01, 0.00000000e+00,
       4.48000000e+02, 4.53200000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 5.90000000e+01, 1.38736500e+03, 0.00000000e+00,
       1.38000000e+02, 1.20000000e+02, 2.22000000e+02, 5.72000000e+02,
       2.37000000e+03, 5.49744700e+03, 0.00000000e+00, 1.58000000e+02,
       0.00000000e+00, 1.00000000e+00, 1.50000000e+01, 8.20000000e+01,
       1.58407000e+02, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 8.00000000e+00, 3.73796000e+02, 2.70000000e+01,
       2.90000000e+01, 0.00000000e+00, 2.25201000e+02, 4.00000000e+00,
       4.00000000e+02, 1.51000000e+03, 1.00000000e+00, 1.00000000e+00,
       7.20000000e+01, 2.80000000e+01, 3.71547000e+02, 1.42400000e+03,
       4.10899000e+02, 1.00000000e+00, 1.30000000e+01, 1.26000000e+02,
       3.85100020e+01, 6.17520000e+01, 5.00000000e+00, 2.72100000e+03,
       1.84700000e+03, 4.04623000e+02, 0.00000000e+00, 1.85703000e+02,
       2.43000000e+02, 4.69000000e+02, 1.00000000e+00, 0.00000000e+00,
       4.30000000e+01, 1.09500000e+03, 0.00000000e+00, 1.17400000e+03,
       1.50000000e+01, 1.00000000e+01, 6.00000000e+00, 1.11000000e+02,
       1.61300000e+03, 1.00361000e+02, 4.50000000e+01, 1.00000000e+00,
       2.70000000e+01, 7.90000000e+01, 1.00000000e+00, 2.06600000e+03,
       1.00000000e+00, 3.00000000e+00, 5.00000000e+00, 3.70000000e+02,
       4.00000000e+00, 2.76000000e+02, 5.58049000e+02, 3.76000000e+02,
       2.00000000e+00, 4.50000000e+01, 1.60586990e+02, 3.49000000e+02,
       2.00000000e+00, 1.20000000e+01, 0.00000000e+00, 1.00000000e+01,
       3.00000000e+00, 1.00000000e+00, 2.40000000e+01, 8.00000000e+00,
       1.50000000e+01, 8.00000000e+00, 5.53100000e+03, 1.46802000e+02,
       2.22600000e+03, 1.85000000e+02, 3.49000000e+02, 6.30000000e+01,
       8.00000000e+00, 3.00000000e+00, 1.21475000e+02, 1.27000000e+02,
       5.00000000e+00, 0.00000000e+00, 2.19000000e+02, 3.00000000e+00,
       2.20000000e+01, 0.00000000e+00, 2.17100000e+03, 0.00000000e+00,
       3.33529000e+02, 4.17000000e+02, 2.10546000e+02, 2.60000000e+02,
       6.74000000e+02, 1.86559500e+03, 4.00000000e+00, 4.33941000e+02,
       5.94200000e+03, 9.67169950e+01, 3.00000000e+00, 8.00000000e+00,
       7.00000000e+00, 2.60000000e+01, 8.00000000e+00, 6.00000000e+00,
       5.00000000e+00, 8.00000000e+00, 4.00000000e+00, 2.04802000e+02,
       1.63000000e+02, 1.57430000e+04, 1.54100000e+03, 0.00000000e+00,
       3.00000000e+00, 2.30000000e+01, 1.83000000e+02, 0.00000000e+00,
       5.70000000e+01, 6.90000000e+01, 1.30000000e+01, 5.37085000e+02,
       4.94000000e+02, 0.00000000e+00, 4.93148000e+02, 2.00000000e+00,
       1.20000000e+01, 1.40000000e+01, 0.00000000e+00, 1.00000000e+01,
       1.36000000e+02, 0.00000000e+00, 1.83291000e+02, 0.00000000e+00,
       6.28150000e+01, 1.20000000e+01, 8.48260000e+01, 4.85400000e+03,
       1.20000000e+01, 1.54000000e+02, 6.16696000e+02, 5.50000000e+01,
       1.50000000e+01, 2.00000000e+00, 2.00000000e+01, 2.31000000e+02,
       0.00000000e+00, 1.05000000e+02, 6.00000000e+00, 3.00000000e+00,
       1.40000000e+01, 2.43316000e+02, 1.60000000e+01, 1.29463000e+02,
       4.21983000e+02, 1.00000000e+00, 5.63000000e+02, 2.30000000e+02,
       4.30490000e+02, 1.80000000e+02, 0.00000000e+00, 7.10000000e+01,
       1.00000000e+00, 8.53549960e+01, 2.00000000e+00, 2.08000000e+02,
       2.27300000e+03, 1.00000000e+01, 1.25700000e+03, 2.96906000e+02,
       6.18929980e+01, 0.00000000e+00, 4.79000000e+02, 0.00000000e+00,
       2.08499010e+02, 0.00000000e+00, 3.20000000e+01, 1.94000000e+02,
       1.00000000e+00, 2.15600000e+03, 8.83340000e+01, 7.38047000e+02,
       1.40000000e+01, 5.78800000e+03, 3.52000000e+02, 2.20000000e+01,
       4.97000000e+02, 5.00000000e+00, 4.70000000e+01, 0.00000000e+00,
       2.56800000e+03, 0.00000000e+00, 1.70000000e+01, 1.04500000e+03,
       2.00000000e+00, 3.78790000e+01, 2.10000000e+01, 1.00000000e+01,
       3.91100000e+02, 2.80000000e+01, 0.00000000e+00, 1.70000000e+01,
       0.00000000e+00, 0.00000000e+00, 3.00000000e+00, 1.00000000e+00,
       0.00000000e+00, 1.45530700e+03, 9.75480000e+02, 2.00000000e+00,
       6.69000000e+02, 0.00000000e+00, 1.00000000e+00, 7.74000000e+02,
       1.98489000e+02, 2.00000000e+00, 1.69610000e+04, 1.10000000e+01,
       3.00000000e+00, 5.99800000e+03, 6.96000000e+02, 2.16000000e+02,
       8.40000000e+01, 6.43100000e+03, 3.23946300e+03, 1.00000000e+01,
       0.00000000e+00, 7.31000000e+02, 9.00000000e+00, 1.70000000e+01,
       9.00000000e+01, 3.00000000e+00, 1.29008180e+04, 5.88125000e+02,
       9.43000000e+02, 1.20000000e+01, 0.00000000e+00, 7.00000000e+00,
       3.00000000e+00, 7.84407000e+02, 4.54850000e+01, 4.40000000e+01,
       0.00000000e+00, 3.60000000e+01, 0.00000000e+00, 1.16000000e+02,
       7.57090000e+01, 1.20000000e+01, 6.00000000e+00, 1.76000000e+02,
       7.00000000e+00, 3.00000000e+00, 3.77674000e+02, 9.36590000e+02,
       4.21000000e+02, 6.00000000e+00, 1.98000000e+03, 3.00000000e+00,
       1.60000000e+01, 1.00000000e+01, 0.00000000e+00, 1.00000000e+00,
       0.00000000e+00, 1.90000000e+01, 9.00000000e+00, 3.00000000e+00,
       1.57000000e+02, 9.00000000e+00, 2.10632000e+02, 0.00000000e+00,
       2.53800000e+03, 2.76000000e+02, 3.10000000e+01, 1.57000000e+02,
       1.00000000e+00, 8.69000000e+02, 3.08000000e+02, 2.00000000e+01,
       8.22846000e+02, 1.26040000e+04, 3.58007000e+02, 2.23900000e+03,
       1.68632800e+03, 1.20000000e+01, 1.00700000e+03, 2.00000000e+00,
       2.00000000e+00, 2.15357000e+02, 2.60000000e+01, 1.28500000e+03,
       2.00000000e+00, 1.60000000e+01, 4.05216000e+02, 0.00000000e+00,
       2.10000000e+01, 2.54737000e+02, 3.70000000e+01, 3.00000000e+00,
       5.32000000e+02, 6.91000000e+02, 1.64609000e+02, 6.00000000e+00,
       1.06637000e+02, 4.14035000e+02, 0.00000000e+00, 3.40000000e+01,
       2.42380000e+01, 2.20000000e+02, 1.00000000e+00, 3.50000000e+01,
       2.10000000e+01, 1.20000000e+01, 1.00000000e+00, 4.34000000e+03,
       0.00000000e+00, 1.79000000e+02, 6.00000000e+00, 1.00000000e+00,
       3.00000000e+00, 0.00000000e+00, 1.81000000e+02, 1.00000000e+00,
       2.69000000e+02, 0.00000000e+00, 2.99255000e+02, 1.45544000e+02,
       0.00000000e+00, 0.00000000e+00, 1.10000000e+01, 1.42109000e+02,
       0.00000000e+00, 5.10000000e+01, 4.40000000e+01, 0.00000000e+00,
       3.20000000e+02, 2.38192000e+02, 1.34000000e+02, 1.82832000e+02,
       3.00000000e+00, 0.00000000e+00, 6.00000000e+00, 1.39195900e+03,
       3.40000000e+01, 1.35062000e+02, 2.20000000e+01, 5.36000000e+02,
       1.71595100e+03, 1.92600000e+03, 1.00000000e+00, 0.00000000e+00,
       2.30000000e+02, 3.71000000e+02, 2.20000000e+01, 1.30000000e+01,
       7.00000000e+00, 4.35750000e+01, 1.96000000e+02, 1.60000000e+01,
       6.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.36313960e+02,
       2.00000000e+00, 1.70000000e+02, 3.00000000e+01, 6.90000000e+01,
       0.00000000e+00, 6.00000000e+00, 2.69000000e+02, 5.00000000e+00])

In [67]:
# sales_array.mean()
product_sales = sales_array[family_array == "PRODUCE"]
product_sales

array([10417.125,  8710.789,  1504.816,  1249.184,  1921.589,  7257.174,
        1416.474,  2810.283,  2049.904,   183.336,  7293.329,  7644.236,
        1363.99 ,   289.345,  1387.365,   537.085,   738.047,  1455.307,
        3239.463, 12900.818,   588.125,   784.407,   936.59 ,   358.007,
        1715.951])

In [68]:
product_sales[rng.random(25) < 0.5].mean()

np.float64(3076.3537692307696)

In [69]:
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]
sales_series = pd.Series(sales, name="Sales")
sales_series

0       0
1       5
2     155
3       0
4     518
5       0
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [70]:
sales_series.values

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [71]:
print(f'The values are : {sales_series.values}')
print(f'The index is : {sales_series.index}')
print(f'The names is : {sales_series.name}')
print(f'The datatype is : {sales_series.dtype}')

The values are : [   0    5  155    0  518    0 1827  616  317  325]
The index is : RangeIndex(start=0, stop=10, step=1)
The names is : Sales
The datatype is : int64

In [72]:
sales_series

0       0
1       5
2     155
3       0
4     518
5       0
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [73]:
sales_series.astype('bool')

0    False
1     True
2     True
3    False
4     True
5    False
6     True
7     True
8     True
9     True
Name: Sales, dtype: bool

In [74]:
sales_series.astype('float')

0       0.0
1       5.0
2     155.0
3       0.0
4     518.0
5       0.0
6    1827.0
7     616.0
8     317.0
9     325.0
Name: Sales, dtype: float64

In [75]:
# sales_series.astype('datetime64')
# ValueError: The 'datetime64' dtype has no unit. Please pass in 'datetime64[ns]' instead.

In [76]:
sales_series

0       0
1       5
2     155
3       0
4     518
5       0
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [77]:
sales_series.head()

0      0
1      5
2    155
3      0
4    518
Name: Sales, dtype: int64

In [78]:
sales_series.describe()

count      10.000000
mean      376.300000
std       557.759018
min         0.000000
25%         1.250000
50%       236.000000
75%       469.750000
max      1827.000000
Name: Sales, dtype: float64

In [79]:
sales_series.loc[1]

np.int64(5)

In [80]:
sales_series.iloc[2]

np.int64(155)

In [81]:
sales_series[sales_series > 10]

2     155
4     518
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [82]:
sales_series[sales_series > 100]

2     155
4     518
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [83]:
sales_series.head()

0      0
1      5
2    155
3      0
4    518
Name: Sales, dtype: int64

In [84]:
sales_series.shape

(10,)

In [85]:
sales_series.describe()

count      10.000000
mean      376.300000
std       557.759018
min         0.000000
25%         1.250000
50%       236.000000
75%       469.750000
max      1827.000000
Name: Sales, dtype: float64

In [86]:
df = sales_series[sales_series > 200]

In [87]:
df

4     518
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [88]:
sales_series

0       0
1       5
2     155
3       0
4     518
5       0
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [89]:
sales_series[2]

np.int64(155)

In [90]:
sales_series[2:5]

2    155
3      0
4    518
Name: Sales, dtype: int64

In [91]:

Sales = [0, 5,5,  155, 0, 518]
Items = ["coffee","coffee", "bananas", "tea", "coconut", "sugar" ]

In [92]:
Sales

[0, 5, 5, 155, 0, 518]

In [93]:
Items

['coffee', 'coffee', 'bananas', 'tea', 'coconut', 'sugar']

In [94]:
Sales_Series = pd.Series(Sales, index=Items, name="Sales")
Sales_Series

coffee       0
coffee       5
bananas      5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [95]:
Sales_Series['coffee']

coffee    0
coffee    5
Name: Sales, dtype: int64

In [96]:
Sales_Series['coffee':'sugar']

coffee       0
coffee       5
bananas      5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [97]:
Sales_Series.iloc[2:4]

bananas      5
tea        155
Name: Sales, dtype: int64

In [98]:
Sales_Series.loc["tea"]

np.int64(155)

In [99]:
Sales_Series.loc["tea":'sugar']

tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [100]:
Sales_Series.loc["tea"]

np.int64(155)

In [101]:
Sales_Series.loc["coffee"]

coffee    0
coffee    5
Name: Sales, dtype: int64

In [102]:
Sales_Series.reset_index()

     index  Sales
0   coffee      0
1   coffee      5
2  bananas      5
3      tea    155
4  coconut      0
5    sugar    518

In [103]:
Sales_Series.loc[Sales_Series > 0]

coffee       5
bananas      5
tea        155
sugar      518
Name: Sales, dtype: int64

In [104]:
mask = (Sales_Series > 0) & (Sales_Series == "tea")
Sales_Series.loc[mask]

Series([], Name: Sales, dtype: int64)

In [105]:
mask = (Sales_Series > 0) & (Sales_Series == "coffee")
Sales_Series.loc[mask]

Series([], Name: Sales, dtype: int64)

In [106]:
Sales_Series == 5

coffee     False
coffee      True
bananas     True
tea        False
coconut    False
sugar      False
Name: Sales, dtype: bool

In [107]:
Sales_Series.eq(5)

coffee     False
coffee      True
bananas     True
tea        False
coconut    False
sugar      False
Name: Sales, dtype: bool

In [108]:
Sales_Series.index.isin(["coffee","tea"])

array([ True,  True, False,  True, False, False])

In [109]:
~Sales_Series.index.isin(["coffee","tea"])

array([False, False,  True, False,  True,  True])

In [110]:
Sales_Series.sort_values()

coffee       0
coconut      0
bananas      5
coffee       5
tea        155
sugar      518
Name: Sales, dtype: int64

In [111]:
Sales_Series.sort_values(ascending=False)

sugar      518
tea        155
bananas      5
coffee       5
coffee       0
coconut      0
Name: Sales, dtype: int64

In [112]:
Sales_Series.sort_index()

bananas      5
coconut      0
coffee       0
coffee       5
sugar      518
tea        155
Name: Sales, dtype: int64

In [113]:
Sales_Series.sort_index(ascending=False)

tea        155
sugar      518
coffee       0
coffee       5
coconut      0
bananas      5
Name: Sales, dtype: int64

In [115]:
oil_df = pd.read_csv(r"C:\Users\TAJ\Desktop\python 101_\data\retail\oil.csv")
oil_df.head()

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [116]:
oil_df.describe()

        dcoilwtico
count  1175.000000
mean     67.714366
std      25.630476
min      26.190000
25%      46.405000
50%      53.190000
75%      95.660000
max     110.620000

In [118]:
oil_df.shape

(1218, 2)

In [119]:
oil_df.dtypes

date           object
dcoilwtico    float64
dtype: object